### ISSUE TITLE
False positive triggering for closure rebinding

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/noverify#10]
## Example

```php
<?php

declare(strict_types=1);

class Example
{
    public function method()
    {
        return 42;
    }
}

(function() {
    $this->method();
})->call(new Example());
```

## Actual

```
ERROR   Undefined variable: this at ...\Example.php:14
    $this->method();
    ^^^^^
ERROR   Call to undefined method {}::method() at ...\Example.php:14
    $this->method();
           ^^^^^^
ERROR   Call to undefined method {}::call() at ...\Example.php:15
})->call(new Example());
    ^^^^
2019/03/02 10:31:06.650272 Found 3 critical reports
```

## Expected

All OK

**Comment by YuriyNasretdinov** [comment]
Did not think about such a case at all :). I will see what we can do, thanks!

**Comment by SerafimArts** [comment]
You can do the same as in the PHP core: https://github.com/php/php-src/blob/76e38289785279748aacc342c5ae45b12e1b4bf7/Zend/zend_compile.c#L1240

The scope is defined for any conditions, except for **anonymous fn** and **traits**. In these exceptional cases, all context references are **late** static, instead of **early**.

**Comment by YuriyNasretdinov** [comment]
> You can do the same as in the PHP core: https://github.com/php/php-src/blob/76e38289785279748aacc342c5ae45b12e1b4bf7/Zend/zend_compile.c#L1240
> 
> The scope is defined for any conditions, except for **anonymous fn** and **traits**. In these exceptional cases, all context references are **late** static, instead of **early**.

Not so easy for static analysis as I do not actually run any code, so there might be no place to do late binding :).

**Comment by SerafimArts** [comment]
I mean that in the source PHP all possible cases are already described in one place when the context cannot be determined i.e. when it is defined in runtime. So for them to determine the identity of the `self` and `$this` is impossible like `static`.
