### ISSUE TITLE
Parsing fails with right-to-left text

### ISSUE THREAD

**Issue by tonygoold** [VKCOM/noverify#107]
## Code Example

```php
<? echo "اُردُو‎\n"; ?>
```

## Actual Behavior

The linter has a syntax error and is unable to examine the file.

```ERROR   syntax: Syntax error: syntax error: unexpected $unk at /path/to/utf8.php:2```

If the text is inside a class method, it can also show up as an "Empty root node" error.

## Expected Behavior

There should be no error.

## Notes

This appears to be a [php-parser issue](https://github.com/z7zmey/php-parser/issues/53) that was fixed, so the solution would be to upgrade the vendored php-parser library to the latest version.

**Comment by quasilyte** [comment]
Can you use NoVerify from `dev-updated-parse` branch for a while and report if there are any new issues with it? We'll close this issue when that branch is merged into a master.

**Comment by tonygoold** [comment]
No new issues so far, except for an unused import I accidentally left in (fixed in https://github.com/VKCOM/noverify/pull/117).
