### ISSUE TITLE
Syntax errors on multiline attributes (PHP8)

### ISSUE THREAD

**Issue by vbifial** [VKCOM/noverify#1085]
## Code Example

```php
<?php

#[MultiLineAttribute(
    field: 'value',
    field2: 'value2',
)]
class MyClass {}
```

## Actual Behavior

```
<critical> ERROR   syntax: Syntax error: syntax error at MyClass.php:4
    field: 'value',
^^^^^^^^^^^^^^^^^^^^
<critical> ERROR   syntax: Syntax error: syntax error at MyClass.php:5
    field2: 'value2',
^^^^^^^^^^^^^^^^^^^^^^
```

## Expected Behavior

No errors found

**Comment by i582** [comment]
Hello
I get these errors only if I set the `--php7` flag, without it, the linter does not find errors in the provided code.

**Comment by vbifial** [comment]
Hello.
I used yesterday's latest release (v0.3.0).
No problems with v0.4.0 release.
Wanted to suggest a compilation of a new release, but you have already done so.
