### ISSUE TITLE
Hello. I get error when I run a ./vendor/bin/noverify-get

### ISSUE THREAD

**Issue by luostary** [VKCOM/noverify#1168]
When I run a command `./vendor/bin/noverify-get` from your Docs/install documentation, I get an error.

You can see full text of error bellow:
**PHP Parse error:  syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) in /home/username/vendor/vkcom/noverify/src/cmd/composer-get/bin/noverify-get on line 91**

Here the screenshot of my error
![image](https://user-images.githubusercontent.com/8068809/143639879-08e26232-cc43-4767-94c9-37926f6ab25f.png)

Can you help me deside this problem?

**Comment by luostary** [comment]
My php version is **7.2.24**

**Comment by i582** [comment]
Hello
It looks like this is due to the new Heredoc syntax, which is handled incorrectly in 7.2.

**Comment by i582** [comment]
As a quick fix, you can remove the quotes on 27 lines around `RR_CLI_ERROR` and then the script should work.

**Comment by luostary** [comment]
Thank you for supporting. I change quotes and script is running.

**Comment by i582** [comment]
> Thank you for supporting. I change quotes and script is running.

Great
