### ISSUE TITLE
LS: add a way to exclude source paths

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#126]
There is a feature request to allow ignoring some source dirs during indexing in language server mode.

The major issue is that these paths that are not meant to be used together may have duplicated symbols. 

Ideally, we want to know whether one or another symbol is accessible from a given location, but given the PHP nature, it can be impossible to have a 100% precise picture.

The proposed solution is to pass either exclude/allow lists that affect language server.
We can add additional pair of arguments for lang server or re-use existing `--exclude` option.

<hr>

Some research on other language servers:

https://github.com/MaskRay/ccls/wiki/Customization
C/C++/Objective-C {index.initialBlacklist} option

https://github.com/snoe/clojure-lsp
Closure {source-paths} option

https://github.com/cquery/project/cquery/blob/master/..
C/C++ {blacklist} option

2 other language servers have `--exclude` as a feture request.
Seems like this feature is not so uncommon.

**Comment by YuriyNasretdinov** [comment]
Yes, that of course makes sense. I was just lazy :).
