### ISSUE TITLE
False negative triggering for IteratorAggregate interface

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/noverify#13]
## Code Example

 ```php
<?php
declare(strict_types=1);

class Example implements \IteratorAggregate
{
    public function getIterator(): array
    {
        return [1, 2, 3];
    }
}

foreach (new Example() as $i) {
    echo $i;
}
```

 ## Actual Behavior

All OK

 ## Expected Behavior

Error: Objects returned by Example::getIterator() must be traversable or implement interface Iterator

**Comment by YuriyNasretdinov** [comment]
It turns out that even for classes that do not implement Traversable, you can foreach() them, so I do not need to check that object implements Traversable, but I can check for errors in this exact case when getIterator() needs to return Traversable.

**Comment by SerafimArts** [comment]
> but I can check for errors in this exact case when getIterator() needs to return Traversable.

It was meant

P.S. I suspect that there are flaws associated with similar interfaces, such as ArrayAccess. For example, when offsetHas returns something other than bool.
