### ISSUE TITLE
Undefined variable for catch clause vars

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#139]
## Code Example

```php
<?php

try {
  throw new Exception(123);
} catch (Exception $e) {}

var_dump($e);
```

## Actual Behavior

```
ERROR   undefined: Undefined variable: e
var_dump($e);
         ^^
```

## Expected Behavior

No warnings by default.
It might emit a warning in strict mode (#83).

If we run that php sctipt with `php -f`:

```
object(Exception)#1 (7) {
  ["message":protected]=>
  string(3) "123"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(34) "~/hello.php"
  ["line":protected]=>
  int(4)
  ["trace":"Exception":private]=>
  array(0) {
  }
  ["previous":"Exception":private]=>
  NULL
}
```

The variable is, in fact, defined.

**Comment by YuriyNasretdinov** [comment]
I would argue that linter should perhaps emit warning that is called "variable might not have been defined" instead as it is closer to what is actually happening: variable `$e` will be only defined if try {} block throws an exception. And, in turn, "variable might not have been defined" may be turned off in "non-strict" mode while the "undefined variable" (the fact that the variable is definitely undefined) should stay.

**Comment by quasilyte** [comment]
Good catch.

**Comment by i582** [comment]
Already done.
