### ISSUE TITLE
Add support of deprecated functions.

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/noverify#15]
## Code Example

 ```php
mysql('a', 'b', 'c');
```

 ## Actual Behavior

All OK

 ## Expected Behavior

Notice: `mysql` function is deprecated since 5.3.0

## Suggest

You can analyze `@deprecated` annotations from phpstorm-stubs (and not only). In addition, `@internal` annotations can be read.

**Comment by YuriyNasretdinov** [comment]
The thing that bothers me a little here is that using deprecated function is not necessarily an error so probably it should not reject push. This makes this check not that important as warnings are usually ignored. Probably I also need to allow to customise which levels should lead to non-zero exit code first.

**Comment by YuriyNasretdinov** [comment]
So we decided to only show warning here, that does not lead to exit-code 2. It will be considered a non-critical issue with MAYBE level.

**Comment by quasilyte** [comment]
I'll take a look into it after we resolve #108.

**Comment by quasilyte** [comment]
Now can be enabled with `-allow-checks=deprecated`.
Maybe will be enabled by default later.

(Feedback is appreciated.)

**Comment by SerafimArts** [comment]
> (Feedback is appreciated.)

I suggest repeating this behavior and for `@internal` annotation. 

...however, there are some differences. Errors should not be selected if the call is made from the same namespace.
