### ISSUE TITLE
Undefined var in foreach if ref is used

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#150]
## Code Example

```php
$xs = [1, 2];

foreach ($xs as &$v) {
    if ($v) {
        var_dump($v);
    }
}
```

## Actual Behavior

```
ERROR   undefined: Undefined variable: v
    if ($v) {
        ^^
```

## Expected Behavior

No error about undefined var.

**Comment by YuriyNasretdinov** [comment]
Is it because the new type for byref was introduced in new version of php-parser?

**Comment by quasilyte** [comment]
Maybe. I had no time to investigate yet.
Your idea sounds realistic though.

**Comment by quasilyte** [comment]
Confirmed. You're right. :)
