### ISSUE TITLE
Hacktoberfest challenge with static analysis

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#191]
Check open-source PHP projects, find bugs with NoVerify, fix them in upstream.

- Choose open-source PHP project
- Run NoVerify on them
- For every critical warning, send PR that fixes it
- If warning is a false positive, report it here

If possible, leave PR links inside this issue comments.

**Comment by i582** [comment]
Doesn't make sense anymore.
Let's create a new issue for the next fest.
