### ISSUE TITLE
Print NoVerify version to stderr during the startup

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#203]
It would be convenient to print the linter version at every execution to stderr by default.

One needs to modify https://github.com/VKCOM/noverify/blob/master/src/cmd/main.go file to achieve that.

Tip: search for "version" inside it.

**Comment by iDevoid** [comment]
Hi @quasilyte
I am new to contribute to open source code? can I try to do this?

**Comment by quasilyte** [comment]
@iDevoid, sure!

**Comment by iDevoid** [comment]
Hi @quasilyte 
would you mind to take a tool to my PR #205 
is it the same as you asked for on this issue?

**Comment by quasilyte** [comment]
Seems like I was not precise enough, sorry.
What I suggested to do is to make noverify print "version" info not only when "-version" is provided but at every execution, probably in a single-line format.

So:
- running with "-version" behaves as before, verbose version info + exit.
- all other executions always print single-line version info.

**Comment by iDevoid** [comment]
I am sorry for misunderstanding, I just updated the code. is the single line format good enough?

**Comment by quasilyte** [comment]
We can always adjust the format later. Thanks!
