### ISSUE TITLE
Separate regression tests from other tests

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#206]
We have several tests that were added to check the resolution of some particular issues.
It would be convenient to separate these regression tests from other tests.

Algorithm:
1. Find bug-reporting issue that was closed with some fix.
2. Usually, that issue contains a commit reference.
3. Check that commit to see whether it added tests (usually, it does).
4. Rename that test in for of `TestIssueXxx`, where `Xxx` is closed issue ID.
5. Send PR with that change.

There can be more than 1 such test. It's OK to send them one-by-one, so it's easier for me to check them (and more people can potentially participate).

The next step would be to place all such tests in a separate file, it can be named, for example, `regression_test.go`.

Note: all linter tests reside in `src/linttest` folder.

**Comment by Abbit** [comment]
Hello, I would like to pick up that

**Comment by Abbit** [comment]
There are some issues (like #26) in which more than 1 test, what name of the tests should be in this situation?

**Comment by quasilyte** [comment]
@Abbit I have an idea, bot for now we can turn them into a single test with 2 t.Run calls or add _2 suffix to one of them. It's a temporary step that is concentrated on finding our regression tests that we can revisit later.

Thank you for doing that work!
