### ISSUE TITLE
Failed parsing: Error renaming tmp file

### ISSUE THREAD

**Issue by Danil42Russia** [VKCOM/noverify#21]
## Steps
1)Execute `go get -u github.com/VKCOM/noverify`
2)Execute 
```
noverify -stubs-dir=D:\\Libs\\phpstorm-stubs -cache-dir=D:\\tmp\\noverify D:\\Dev\\php\\RobotSharpApi -exclude='vendor/'
```

## Actual
Many similar mistakes: 
```
Failed parsing D:\Libs\phpstorm-stubs\zmq\zmq.php: rename D:\tmp\noverify\D_\Libs\phpstorm-stubs\zmq\zmq.php.4687de6d3e2dce931ca5e9470c5b8079.tmp D:\tmp\noverify\D_\Libs\phpstorm-stubs\zmq\zmq.php.4687de6d3e2dce931ca5e9470c5b8079: The process cannot access the file because it is being used by another process.
Failed parsing D:\Dev\php\TestProject\src\Api\ApiLogin.php: rename D:\tmp\noverify\D_\Dev\php\TestProject\src\Api\ApiLogin.php.e3e9f90751d8aba6be7c13558e537d91.tmp D:\tmp\noverify\D_\Dev\php\TestProject\src\Api\ApiLogin.php.e3e9f90751d8aba6be7c13558e537d91: The process cannot access the file because it is being used by another process.
```

## Expected
No error

**Comment by YuriyNasretdinov** [comment]
I suppose this happened after a version update, when cache folder was not empty? It shouldn't show any errors when you run it on an empty folder and if you don't update the cache version. Is it correct? I do not test linter on windows (yet) so I would like to collect more details before fixing the issue :).

**Comment by YuriyNasretdinov** [comment]
Oh, I actually got a Windows machine to test on :). There are two reasons for failure:
1) I rename file before closing it — Windows does not support that
2) You cannot replace existing file on Windows using rename (the latter is not your case but that can be a problem in the future)
