### ISSUE TITLE
Handle malformed type-name pairs in @property phpdoc attrs

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#231]
When handling `@param`, we can guess that the user probably messed up with type and name order in phpdoc:
```diff
-@param $name type
+@param type $name
```
We swap phpdoc line fields in this case:

https://github.com/VKCOM/noverify/blob/fd8067ab30f7e501e58d52056f6cbb0a51e22453/src/linter/root.go#L992-L996

Line 995 does the swapping.

We don't perform such correction for `@property` attributes.

This issue is about applying the same fixes to somewhat oddly formed `@property` lines.

Relevant code can be found in `root.go` (code above is listed from there).

Adding tests for it is a requirement.

**Comment by MrYadro** [comment]
Should be fixed in #242

**Comment by quasilyte** [comment]
Thanks!
