### ISSUE TITLE
Unused false positive in switch

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#241]
## Code Example

```php
<?php

function f($v) {
    switch ($v) {
        case 1:
            $x = 100;
            break;
        default:
            echo "branch that doesn't define x, nor return";
    }
    var_dump($x);
}
```

## Actual Behavior

2 warnings:
```
<critical> INFO    undefined: Variable might have not been defined: x at hello.php:11
    var_dump($x);
             ^^
<critical> UNUSED  unused: Unused variable x (use $_ to ignore this inspection) at hello.php:6
            $x = 100;
            ^^
```

## Expected Behavior

Only 1 warning (about potentially undefined var).

**Comment by YuriyNasretdinov** [comment]
This definitely doesn't make sense and it is an artifact of how we handle unused variables and it needs to be fixed. PHP scopes are not the same as C scopes so we need to follow PHP rules instead.

**Comment by quasilyte** [comment]
So it's not a by-design behavior. OK, marking as a bug then.

**Comment by i582** [comment]
Already done.
