### ISSUE TITLE
linttest: load builtin stubs for every test by default

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#250]
It's not very convenient to define `null`, `false`, etc (and `define` function itself) inside every test where the builtin constant is needed.

linttest should load these symbols by default as stubs.

**Comment by YuriyNasretdinov** [comment]
I don't do this for performance reasons — it takes ~0.3 sec to load all the stubs. Multiply by the number of tests and it quickly becomes a bottleneck.

It's probably ok to load some common ones though.

**Comment by i582** [comment]
We are already loading some stubs for tests.
