### ISSUE TITLE
Colon code-design

### ISSUE THREAD

**Issue by Levsha-cc** [VKCOM/noverify#252]
## Code Example

We using colon code-design in our templates. 

```php
<?php
$array = [1,2,3,5,6,7];

// Example 1 - what we use
foreach ($array AS $key => $value):
    var_dump($key, $value);
endforeach;

// Example 2
foreach ($array AS $key => $value) {
    var_dump($key, $value);
}
```

## Actual Behavior

In example 1 I got next errors:
```
<critical> ERROR   undefined: Undefined variable: key at playlist.php:5
foreach ($array AS $key => $value):
                   ^^^^
<critical> ERROR   undefined: Undefined variable: value at playlist.php:5
foreach ($array AS $key => $value):
                           ^^^^^^
2019/10/18 19:14:34.210389 Found 2 critical reports
```

And no errors in example 2

## Expected Behavior

No error in both examples, and example 1 should have same behavior as example 2.

**Comment by Levsha-cc** [comment]
Also checked this file with  github.com/z7zmey/php-parser and got only one difference: example 1 is [*stmt.AltForeach] and example2 is [*stmt.Foreach]. Body cycles are the same, so I'm affraid the problem on your side :)

**Comment by quasilyte** [comment]
I think NoVerify doesn't handle `Alt*` structures well enough. In theory, it's possible to fix with some additional code, but I would expect #111 to be beneficial here if we will convert both forms into a single structure.

**Comment by Levsha-cc** [comment]
Thank you!
