### ISSUE TITLE
Failed parsing: If condition containing isset with variable variable expression

### ISSUE THREAD

**Issue by tonygoold** [VKCOM/noverify#26]
When an if condition contains an isset that uses a "variable variable", `linter.(*BlockWalker).handleIf` panics because it expects a `*node.Identifier` for the variable name instead of a `*expr.Variable`.

## Code Example

```php
function get_global_var($name) {
    global $$name;
    if (isset($$name)) { // Panic occurs while parsing this line
        return $$name;
    }
    return null;
}
```

## Actual Behavior

```
Panic while parsing <filename>: interface conversion: node.Node is *expr.Variable, not *node.Identifier
```

## Expected Behavior

No panic.

**Comment by YuriyNasretdinov** [comment]
Wow, didn't know that you can write isset this way :). Thank you for the report, I'll add some checks for that.

**Comment by YuriyNasretdinov** [comment]
Should be fixed now.
