### ISSUE TITLE
Linter often crashes: concurrent map read and map write

### ISSUE THREAD

**Issue by sergey-shambir** [VKCOM/noverify#274]
## Code Example

No minimized code, crash happens on random projects on 20-40% launches (repeating ~10 times is enough to reproduce).
Reproducable on [github.com/andreafiori/symfony-3-todo-list](https://github.com/andreafiori/symfony-3-todo-list) with command `noverify .`

## Actual Behavior

Linter crashes with fatal error and stacktrace
```
fatal error: concurrent map read and map write
```
Full stacktrace: https://gist.github.com/sergey-shambir/9b77fc1d6bda9267ea35fcdab77b2620

## Expected Behavior

Linter does not crash after 10-20 launches.

**Comment by quasilyte** [comment]
Should be fixed on master and v0.1.0 release. Could you verify?

**Comment by sergey-shambir** [comment]
Looks like it fixed: cannot reproduce crash after 20 attempts.
