### ISSUE TITLE
Decide on multi-pattern rules syntax

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#276]
This discussion is about new NoVerify feature: [dynamic rules](https://github.com/VKCOM/noverify/blob/master/docs/dynamic-rules.md).

You can also check #269 and #275 to get some insights.

## Feature overfiew

Before we get into details, here is a terminology hint: a **rule** is a **phpdoc comment** describing inspection properties plus a **phpgrep pattern** that describes a syntax to be matched by that rule.

Some rules require multiple patterns to become more exhaustive. This sometimes leads to phpdoc blocks duplication.

In the example below we see the same comment copied in 3 rules:

```php
/** 
 * @maybe ++ can only affect ints and strings 
 * @type $x array|object|bool
 */
$x++;

/** 
 * @maybe ++ can only affect ints and strings 
 * @type $x array|object|bool
 */
++$x;
```

This feature is a proposal to allow "pattern grouping" or "pattern combination" that allows us to spell phpdoc only once:

```php
/** 
 * @maybe ++ can only affect ints and strings 
 * @type $x array|object|bool
 */
$x++;
++$x;
```

The only question remains: which exact syntax should we use for it? One option is demonstrated in the example itself, but there are other options.

> We could use "not int AND not string" type constraint, but it's not implemented yet.

How this poll is supposed to go:
1. I'll post all proposed options here, in this first message. All new options are prepended. Listed options are links that lead to a thread message.
2. To vote for an option, you can add :+1: on a message that describes it.

If you're about to add a new syntax option, please take a look for existing proposals and try to keep your message formatting and wording consistent with already proposed options. Thank you.

Here is a basic "template":

<pre>
### Votable idea

Idea description.

```php
/**
 * @maybe ++ can only affect ints and strings
 * @type $x array|object|bool
 */
{
  $x++;
  ++$x;
}
```

</pre>

## Options

* https://github.com/VKCOM/noverify/issues/276#issuecomment-548539645 No explicit syntax
* https://github.com/VKCOM/noverify/issues/276#issuecomment-548539768 Grouping with {}
* https://github.com/VKCOM/noverify/issues/276#issuecomment-548547159 Wrap inside a function body

**Comment by quasilyte** [comment]
### Votable idea

Omitting phpdoc comment from a pattern connects it with the previous pattern.

```php
/**
 * @maybe ++ can only affect ints and strings
 * @type $x array|object|bool
 */
$x++;
++$x;
```

**Comment by quasilyte** [comment]
### Votable idea

When patterns combination is needed, {} block should be used.

```php
/**
 * @maybe ++ can only affect ints and strings
 * @type $x array|object|bool
 */
{
  $x++;
  ++$x;
}
```

**Comment by YuriyNasretdinov** [comment]
### Votable idea

Extension of the previous idea: declare "pseudo-functions" to also assign every custom rule a name so that you can disable it, group by it, etc.

It makes it look more like a normal PHP code, allows to use IDE to edit and navigate the file more easily.

```php
/**
 * @maybe ++ can only affect ints and strings
 * @type $x array|object|bool
 */
function nvf_incrementProperTypes() {
  $x++;
  ++$x;
}
```

**Comment by quasilyte** [comment]
For the record, functions per rule group worked well in https://github.com/quasilyte/go-ruleguard
