### ISSUE TITLE
Improve type inference for array literals

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#285]
## Code Example

```php
<?php

class Foo { public $value = 1; }
$xs = [new Foo()];
```

## Actual Behavior

Type of `$xs` is inferred as `array` (`mixed[]`), while it could be `Foo[]`. We do make precise inference for `[]int` and other scalar types, so it's a matter of that algorithm improvement.

## Expected Behavior

Type of `$xs` inferred as `Foo[]`.

**Comment by i582** [comment]
Already fixed.
