### ISSUE TITLE
Parsing of array<K,V>-like types from phpdoc

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#290]
## Code Example

```php
<?php

class Foo { public $value = 1; }

/**
 * @param array<int,Foo> $xs
 */
function f($xs) {
  return $xs[0]->value;
}
```

## Actual Behavior

```
MAYBE   arrayAccess: Array access to non-array type \array<int,Foo> at /home/isharipov/CODE/php/hello.php:9
  return $xs[0]->value;
         ^^^
<critical> ERROR   undefined: Property {mixed}->value does not exist at /home/isharipov/CODE/php/hello.php:9
  return $xs[0]->value;
                 ^^^^^
```

## Expected Behavior

No warnings.

This notation is not very popular, but we should at least try not to interpret it as `\array<int,Foo>` class. Throwing away key type info is OK-ish, we could record that param type as `Foo[]`.

**Comment by YuriyNasretdinov** [comment]
Also need to be able to parse `list<type>`, `non-empty-list<type>`

**Comment by YuriyNasretdinov** [comment]
Also `array<type>`

**Comment by YuriyNasretdinov** [comment]
Also `array{key1: type1, ..., keyN: typeN}` where key1, ..., keyN are names of the keys in the array (or their indexes).
