### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by dereuromark** [VKCOM/noverify#305]
https://github.com/VKCOM/noverify/blob/master/docs/install.md

Documentation says

    git clone github.com/VKCOM/noverify $GOPATH/github.com/VKCOM

> fatal: repository 'github.com/VKCOM/noverify' does not exist

The valid Git URL to work is

    https://github.com/VKCOM/noverify.git

so:

    git clone https://github.com/VKCOM/noverify.git $GOPATH/github.com/VKCOM

**Comment by quasilyte** [comment]
I can confirm that you're right.
Do you want to send a PR or it's OK for someone else to send a fix?

**Comment by dereuromark** [comment]
I am ok with anyone updating docs :)
