### ISSUE TITLE
Support nullable types

### ISSUE THREAD

**Issue by YuriyNasretdinov** [VKCOM/noverify#340]
## Code Example

```php
<?php
class A {
/** @var ?B */
public $b;
}

class B {
public $c;
}

function test() {
return (new A)->b->c;
}
```

## Actual Behavior

Property {\?B}->c does not exist

## Expected Behavior

Either no errors or warning that {A->b} might be null.

**Comment by quasilyte** [comment]
We have nullable types parsing support, but it's not used yet. :)

**Comment by YuriyNasretdinov** [comment]
You can also just specify "A|null" and it will also work :). We just need to start using this.
