### ISSUE TITLE
Refactor phpdoc parsing implementation

### ISSUE THREAD

**Issue by YuriyNasretdinov** [VKCOM/noverify#344]
While it started as a very simple piece of code, it is apparent that because of complexity that modern PHP codebases allow we need a full-fledged parser for PHPDoc similar to the PHP parser we have right now. We also need to try to make sure that types that come from PHPDoc are parsed in the same way as in regular PHP when PHP syntax allows it.

**Comment by quasilyte** [comment]
We already have a dedicated types parser that supports all kinds of phpdoc-permitted types.
Examples:
https://github.com/VKCOM/noverify/blob/master/src/phpdoc/type_parser_test.go
It produces an AST that can be then converted to a linter-compatible types representation.

**Comment by YuriyNasretdinov** [comment]
Yeah, I saw that. I meant that we need to extend it to support `T<A,...>` as well as `array{key: value, ...}` and remove or heavily limit all manual PHPDoc parsing that we are currently doing, otherwise it would be pain to support this code in the future.

**Comment by i582** [comment]
Already done.
