### ISSUE TITLE
need better option for "exclude" param - trying to check Bitrix project or WordPress or other CMS

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [VKCOM/noverify#350]
## Code Example

`noverify -exclude "bitrix/modules/b24connector|bitrix/modules/fileman|bitrix/modules/main|bitrix/modules/search|bitrix/modules/ui|bitrix/modules/bitrixcloud|bitrix/modules/highloadblock|bitrix/modules/messageservice|bitrix/modules/seo|bitrix/modules/clouds|bitrix/modules/iblock|bitrix/modules/perfmon|bitrix/modules/socialservices|bitrix/modules/compression|bitrix/modules/landing|bitrix/modules/rest|bitrix/modules/translate" -output noverify.log -stubs-dir=$HOME/bin/phpstorm-stubs -cache-dir=upload/tmp/noverify -exclude-checks arraySyntax,phpdoc,phpdocLint,phpdocType bitrix/modules`

- i have my own module or plugin in standart CMS directory and need to check only this module/plugin

- i need exclude all folders of CMS/framework/whathever from checking

- in simmple example i have this modules - how to exclude them all?

now i should add all project structure 
except my own folder: bitrix/modules/partner.megasolution

**Comment by 6umpukc-uHKBu3umop** [comment]
`noverify -include "bitrix/modules/partner.megasolution" -output noverify.log -stubs-dir=$HOME/bin/phpstorm-stubs -cache-dir=upload/tmp/noverify -exclude-checks arraySyntax,phpdoc,phpdocLint,phpdocType bitrix/modules

`
or 

`noverify -includefiles phpfiles_list.txt -output noverify.log -stubs-dir=$HOME/bin/phpstorm-stubs -cache-dir=upload/tmp/noverify -exclude-checks arraySyntax,phpdoc,phpdocLint,phpdocType bitrix/modules

**Comment by quasilyte** [comment]
Hello @6umpukc-uHKBu3umop.

> let's check only files by mask

You can already do that by either passing an appropriate lint target arguments or, if you need to index other parts of the project as well, by specifying `full-analysis-files` argument.

For example, `noverify --full-analysis-files=bitrix/modules /path/to/project` would index the entire project, but warnings are produced only for files matching `full-analysis-files`.

`--exclude` usually used for vendor folders. If you want to check a specific project part, use `full-analysis-files` flag.

Hope that helps.

**Comment by 6umpukc-uHKBu3umop** [comment]
thanks
