### ISSUE TITLE
Make tinygo able to compile noverify & make it work too

### ISSUE THREAD

**Issue by YuriyNasretdinov** [VKCOM/noverify#355]
There are several things that tinygo (https://tinygo.org/webassembly/webassembly/) does not support for webassembly:

- calling external programs using os.Exec()
- calling any callbacks (e.g. just `func()`) makes functions async which makes it impossible to call them from a handler
- not all expressions are supported as default values (e.g. `regexp.MustCompile()` does not work, as well as having loops like in `fallthroughMarkerRegex` initialisation code)
- `encoding/json` and `encoding/gob` are not supported at all (lacking some reflection support?)
- `sync/atomic` not supported in `wasm` mode
- `reflect.DeepEqual` is not supported
- reading from nil map causes panic (not 100% sure about that)

The commit that makes tinygo 0.12.0 at least compile although it deletes a lot of functionality: https://github.com/YuriyNasretdinov/noverify/commit/77f463ce525e0173d61c136dfdf184642771a060

It is probably possible to extract core parser/linter logic from I/O operations and other things that are mentioned above. Probably some code can be compiled conditionally (i.e. git operations don't make sense for wasm).

Anyway, tinygo seems to be work-in-progress so probably some issues will be resolved in future releases.

**Comment by i582** [comment]
It seems this is already very outdated.
