### ISSUE TITLE
Improve detection with class_exists/method_exists cases

### ISSUE THREAD

**Issue by TrogWarZ** [VKCOM/noverify#362]
I use that kind of checks (with `class_exists`+`method_exists` combo) regularly in my libraries to decide what algorithm to use. And i don't want to use `-exclude-checks` because it skips really bad cases in project.

## Installation and steps to reproduce

```bash
# I'm using osx
brew install go
# Installing noverify
mkdir -p $GOPATH/github.com/VKCOM
git clone https://github.com/VKCOM/noverify.git $GOPATH/github.com/VKCOM
cd $GOPATH/src/github.com/VKCOM/noverify
make install
# Use it as a static linter
cd /path/to/symfony3/project
noverify -exclude='vendor/|tests/|tmp/|var/' .
```

## Code Example

For example, this is what i've found after checking in my Symfony v3 project in file `bootstrap.php`:

```php
$path = dirname(__DIR__).'/.env';

if (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
}

$dotenv = new Dotenv();
if (method_exists($dotenv, 'loadEnv')) {
    $dotenv->loadEnv($path); // <–– Critical is here
}
```

## Actual Behavior

```
<critical> ERROR   undefined: Call to undefined method {\Symfony\Component\Dotenv\Dotenv}->loadEnv() at /path/to/symfony3/project/app/bootstrap.php:9
        $dotenv->loadEnv($path);
                 ^^^^^^^
```

## Expected Behavior

No error here must be :-)

**Comment by quasilyte** [comment]
Hello. Thank you for the report!

Suppose we do treat `method_exists` is a special way and linter known that a method with such name can exist. There is a problem that we don't know anything else except its name. We can't check the number of arguments, their types or method return type.

It's not too hard to imply a function that takes any number of arguments and returns a mixed-typed result, but it would be nice to figure out a more typesafe alternative for that so it can be suggested there.

**Comment by quasilyte** [comment]
I'm not 100% sure what to do with `class_exists` though if that class does not exist locally.

We can avoid reporting errors when its name is referenced, but we can't check anything related to the variables that have such type.

**Comment by TrogWarZ** [comment]
Thanks for fast reply!

So, instead, i should use `class_exists` and `instanceof` check? Well, here is still same problem with that one. Maybe, after `class_exists` linter can analyze that class?

I don't know how common is that case.. but.. sometimes in my work i don't know which version i have in runtime right now (sad, but old legacy is exists). Like, for example with Dotenv – method was added only in v4.2 and i have projects still using old version.. and they don't have that method so `instanceof` check is not useful and can lead to fatals in runtime.

Is that case is possible to solve with additional mechanisms in linter? Sorry, i don't have experience with coding those projects so maybe question sounds stupid (-:
Or, at least, those critical warnings can be muted specifically after `method_exists` checks?

**Comment by quasilyte** [comment]
I gathered some info from other PHP developers.

It seems like `method_exists` is a somewhat common thing when you're trying to support several versions (just as you mentioned as well).

I'll try making `method_exists` work.
