### ISSUE TITLE
if-related invariants not erased before handling else branch

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#363]
## Code Example

```php
<?php

class C {
  /***/
  public function example() {}
}

function f($c) {
  if ($c instanceof C) {
  } else {
    $c->example();
  }
}

```

## Actual Behavior

No warnings.

## Expected Behavior

Calling to undefined method, since `$c` is **not** C-typed.

**Comment by quasilyte** [comment]
This is not only about instanceof but rather about all things recorder from `if`.

```php
function f() {
  if (isset($x)) {
  } else {
    var_dump($x);
  }
}
```
This code gives no warning about undefined `$x`.

**Comment by quasilyte** [comment]
Another observation:

```php
if (isset($x) && $foo = 10) {}

var_dump($foo);
```

The code above does not generate any warnings because we treat everything in `if` condition as evaluated unconditionally.

It should probably report usage `$foo` as "might not be defined".

**Comment by i582** [comment]
Done by #1058
