### ISSUE TITLE
php/parser: generate one type of ElseIf for both `elseif` and `else if`

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#365]
It's easier to have a single type of `elseif` instead of having to handle `stmt.ElseIf`+`stmt.Else+If` all the time. Semantically, there is no difference.

To avoid losing syntax information, we can store a flag or something that makes it possible to distinguish between them if we ever want to do that.

**Comment by YuriyNasretdinov** [comment]
Yes, I couldn't agree more. It is very painful currently to handle elseif statements because of that.
