### ISSUE TITLE
Consider a transition to ragel-based lexer

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#381]
Upstream [php-parser](https://github.com/z7zmey/php-parser/) did a transition to Ragel-based lexing.

Synthetic benchmarks show a significant performance boost, around x2 parsing speed just by making lexer faster (is `golex` that ineffective?).

I compared a Ragel-based NoVerify on [symfony](https://github.com/symfony/symfony) repository.
So far it seems like we get around 5-10% speedup (more work is required to get numbers with better precision).

golex profile:
```
Showing nodes accounting for 5140ms, 38.88% of 13220ms total
Dropped 460 nodes (cum <= 66.10ms)
Showing top 10 nodes out of 209
      flat  flat%   sum%        cum   cum%
     930ms  7.03%  7.03%     1840ms 13.92%  runtime.scanobject
     870ms  6.58% 13.62%     7120ms 53.86%  github.com/VKCOM/noverify/src/php/parser/php7.(*yyParserImpl).Parse
     650ms  4.92% 18.53%      900ms  6.81%  runtime.findObject
     610ms  4.61% 23.15%     2730ms 20.65%  runtime.mallocgc
     540ms  4.08% 27.23%      710ms  5.37%  runtime.heapBitsSetType
     360ms  2.72% 29.95%     3170ms 23.98%  github.com/VKCOM/noverify/src/php/parser/scanner.(*Lexer).Lex
     350ms  2.65% 32.60%      930ms  7.03%  runtime.wbBufFlush1
     310ms  2.34% 34.95%      850ms  6.43%  github.com/VKCOM/noverify/vendor/github.com/cznic/golex/lex.(*Lexer).next
     280ms  2.12% 37.07%      780ms  5.90%  runtime.gcWriteBarrier
     240ms  1.82% 38.88%      270ms  2.04%  runtime.spanOf (inline)
```
ragel profile:
```
Showing nodes accounting for 5030ms, 46.15% of 10900ms total
Dropped 392 nodes (cum <= 54.50ms)
Showing top 10 nodes out of 222
      flat  flat%   sum%        cum   cum%
    1220ms 11.19% 11.19%     2170ms 19.91%  runtime.scanobject
     780ms  7.16% 18.35%     4790ms 43.94%  github.com/VKCOM/noverify/src/php/parser/php7.(*yyParserImpl).Parse
     760ms  6.97% 25.32%      930ms  8.53%  runtime.findObject
     430ms  3.94% 29.27%     2500ms 22.94%  runtime.mallocgc
     420ms  3.85% 33.12%     1090ms 10.00%  github.com/VKCOM/noverify/src/php/parser/scanner.(*Lexer).Lex
     410ms  3.76% 36.88%      570ms  5.23%  runtime.heapBitsSetType
     290ms  2.66% 39.54%      290ms  2.66%  runtime.memclrNoHeapPointers
     260ms  2.39% 41.93%      260ms  2.39%  runtime.markBits.isMarked (inline)
     250ms  2.29% 44.22%      250ms  2.29%  runtime.nextFreeFast (inline)
     210ms  1.93% 46.15%      660ms  6.06%  runtime.gcWriteBarrier
```
It looks like we spend less time in lexer-related code.

Most savings are in `user` time probably due to the highly parallel nature of NoVerify. We cut around 10% of `user` time spent on average.

My main rationale to make this switch is compatibility with the upstream repository to make it easier to port patches in both directions. Since we don't lose anything, it might be a right decision.

**Comment by quasilyte** [comment]
I found several backward-incompatible changes in a new Lexer API:
- Parser-related code needs to be changed a bit.
- It seems like now we don't need to subtract 1 from `Pos.StartPos` anywhere.

Everything else seems to be OK.

**Comment by YuriyNasretdinov** [comment]
Yeah I also noticed that golex wasn't super efficient. Does ragel-based parser still require everything to be UTF-8? Because PHP itself doesn't have this requirement so not having to convert encodings and interpret everything as runes would also save some CPU cycles.

Anyway, I support that effort 100%. Parsing is still a major part of NoVerify CPU time and it's good to see any improvements there.

**Comment by quasilyte** [comment]
Ragel lexer can handle non-UTF8 encodings.

We can simplify the `ParseContents` function and remove `inputs` package, but I opted to be conservative for now until we get more chances to see how new setup behaves.
