### ISSUE TITLE
Don't treat only writing to (and never reading from) an array as a usage

### ISSUE THREAD

**Issue by YuriyNasretdinov** [VKCOM/noverify#388]
## Code Example

```php
<?php
function f2($result) {
    foreach ($result as &$file) {
        $file['filesystem'] = 'ntfs';
    }
}
```

## Actual Behavior

$file is unused (incorrect)

## Expected Behavior

$result is unused (only writes and no reads, and an array was passed by value)

**Comment by quasilyte** [comment]
I think that diagnostic can be the right place to warn about `$arr` as being "effectively unused" in  code below:
```php
function f() {
  $arr = [];
  // ...some code
  $arr['key'] = 10;
  // after that $arr is never useda again
}
```

**Comment by YuriyNasretdinov** [comment]
Yes, that also counts
