### ISSUE TITLE
Incorrect path definition for cache

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/noverify#4]
## Steps To Reproduce

1) Execute `go get -u github.com/VKCOM/noverify`
2) Execute `git clone git@github.com:JetBrains/phpstorm-stubs.git D:\\php\\phpstorm-stubs`
3) Execute `noverify -stubs-dir=D:\\php\\phpstorm-stubs -cache-dir=./cache ./src`

## Actual

1) Multiple errors like: `Failed parsing D:\php\phpstorm-stubs\zend\zend_f.php: open .cache\D:\php\phpstorm-stubs\zend\zend_f.php.e3a8c59daf7cb0d1249aa10a581ba9a9.tmp: The filename, directory name, or volume label syntax is incorrect.`

## Expected

All OK

## Suggest

Add support for relative paths

**Comment by YuriyNasretdinov** [comment]
Should be fixed. Please feel free if the fix did not help. I do not really have a windows machine to test on :)
