### ISSUE TITLE
Output to unit testing xml report

### ISSUE THREAD

**Issue by johnwc** [VKCOM/noverify#426]
To really help in using in CI builds, it would be nice to have it support being able to write the findings to a XML file. Most CI frameworks know how to read [NUnit ](https://github.com/nunit/docs/wiki/Test-Result-XML-Format) or [JUnit](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) formatted xml docs and report on them.

**Comment by quasilyte** [comment]
Hello, @johnwc!

NoVerify supports JSON output.

I'll take a look at the provided links. It's possible to add another output format, but maybe it's easier to add them on top of the JSON, so that tool would convert JSON into any desired format.
