### ISSUE TITLE
Expr type: bitwise or/and/xor over strings should give string type

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#442]
https://www.php.net/manual/en/language.operators.bitwise.php

> If both operands for the &, | and ^ operators are strings, then the operation will be performed on the ASCII values of the characters that make up the strings and the result will be a string. In all other cases, both operands will be converted to integers and the result will be an integer. 

```php
<?php

$x = 'foo';
var_dump($x & 'bar'); // => 'bab'
```

**Comment by quasilyte** [comment]
Seems like `~` can also work with strings:
```
If the operand for the ~ operator is a string, the operation will be performed on the ASCII values of the characters that make up the string and the result will be a string, otherwise the operand and the result will be treated as integers. 
```

**Comment by YuriyNasretdinov** [comment]
Honestly I think we need to give a warning when this functionality is used instead. It's not very obvious that it can happen.

**Comment by quasilyte** [comment]
That's a separate issue.
Type inference must be precise and follow a language logic.
