### ISSUE TITLE
Add @pure attribute for matched expressions

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#465]
Many times it's useful to check if matched expression can be safely removed or replaced.

We need to expose `sideEffectFree(x)` predicate for the dynamic rules through `@pure` filter.

```php
/**
 * @name ternarySimplify
 * @maybe use ?: shorthand for $a?$a:$b case
 * @pure $x
 */
$x ? $x : $y;
```
Without `@pure`, rule above can sometimes suggest invalid replacements.

```php
f() ? f() : $x
```
If `f()` has side effects, the original code would evaluate it twice while `f() ?: $x` would only do so once.

**Comment by YuriyNasretdinov** [comment]
I fully agree
