### ISSUE TITLE
Add support to progress in lang-server

### ISSUE THREAD

**Issue by edgardmessias** [VKCOM/noverify#484]
To create a progress notification in lang-server:
Create a progress request: [window/workDoneProgress/create](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_workDoneProgress_create) and wait the response

Notify the progress: [$/progress](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress), where `T` can be:
* [WorkDoneProgressBegin](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgressBegin)
* [WorkDoneProgressReport](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgressReport)
* [WorkDoneProgressEnd](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgressEnd)

**Comment by YuriyNasretdinov** [comment]
I was going to say that I don't remember it being possible before... And indeed, when I implemented the LSP prototype, only version 2 was out and now it's 3.15. I definitely don't mind there being a progress indicator although it probably won't be able to tell how many files are left to index because directories are traversed as files are parsed.

**Comment by edgardmessias** [comment]
It is a not problem, we can send only the `begin` and `end` and the editor keeping showing "Indexing files..."

As a alternative, we can use the `report` to show what is the current folder is indexing

**Comment by YuriyNasretdinov** [comment]
I would suggest doing something like sending "report" every Nth file being indexed. Files should be indexed pretty quickly (~1M SLOC/sec when cache is on, so if an average file is ~100-1000 SLOC it would mean that it indexes 1,000-10,000 files per second) so if we report every, e.g. ~500th file, it shouldn't overwhelm VSCode but report enough progress to the user to make sure they can see that the indexing process is still going.

**Comment by YuriyNasretdinov** [comment]
(the advantage over reporting every directory is that not all directories contain PHP files, most notably node_modules, for example)

**Comment by i582** [comment]
Doesn't make sense anymore.
