### ISSUE TITLE
Add identifier position for classes, methods, funcions..

### ISSUE THREAD

**Issue by edgardmessias** [VKCOM/noverify#488]
It is really interesting for language server, because we can use in Goto Declaration, Goto Definition, ...

* Class
* Method
* Funcion
* Property
* Constant

**Comment by YuriyNasretdinov** [comment]
I think it is already there though. Or almost there, as I am pretty sure that the line number is already stored. Because go-to-definition should be working already (at least for simple cases like constants, functions, etc)

**Comment by quasilyte** [comment]
![image](https://user-images.githubusercontent.com/6286655/83286729-13cee700-a1e9-11ea-87fc-f1339f0662c3.png)

For example, ClassInfo:
https://github.com/VKCOM/noverify/blob/2a7d83841bd8f57337d412593203f54fd9ba5e63/src/meta/metainfo.go#L371-L373

`Pos` is a field that you're looking for. If we're missing Pos field anywhere, they can be added.

**Comment by edgardmessias** [comment]
Currently there are the pos of full statement

https://github.com/VKCOM/noverify/blob/2a7d83841bd8f57337d412593203f54fd9ba5e63/src/linter/root.go#L898

My suggestion is create thing like this:

```go
IdentPos:          d.getElementPos(meth.MethodName),
```

**Comment by edgardmessias** [comment]
The `Pos` is not wrong, it used in DocumentSymbol to show the correct position
The `IdentPos` would used for "GoTo ..."

**Comment by YuriyNasretdinov** [comment]
Oh, you mean to store the position of the class name element instead of the beginning of "class Xxx { ... }" statement. Yes, I agree, that would be more accurate. Would you like to do this?

**Comment by quasilyte** [comment]
I see. We can store additional positions.

The only downside is that it can affect the cache size.
It's also quite a waste to store several element positions that include a filename...

--

A little off-topic.

I like how it's done in `go/ast` and `go/token`.

They have `token.Pos` which is super efficient and `token.Position` that has full information. Most nodes have `token.Pos` which can be converter to `token.Position` with a help of `token.FileSet`.

We can, in theory, use `go/token` ourselves, but I'm not 100% sure how we could save `token.FileSet` to disk.

**Comment by YuriyNasretdinov** [comment]
I don't think we need to store _two_ positions. Position is only used in a language server anyway so if we make it more accurate that's fine I think.

**Comment by quasilyte** [comment]
The point with `go/token` still stands. :)
It's one of the best positions approaches I've seen so far.

**Comment by YuriyNasretdinov** [comment]
Sure. As far as I know, php-parser uses ast/token to store positions under the hood anyway.

**Comment by edgardmessias** [comment]
Yes, we can use the ast/token to get the correct possition. Besides that, It allow get the "phpdoc comment", and use for "hover" and "function signatures"

My question: how can I get the "ast" from "ClassInfo"?

**Comment by YuriyNasretdinov** [comment]
You can't do it at the moment. I guess Iskander has some ideas on how to do this :)

**Comment by i582** [comment]
Doesn't make sense anymore.
