### ISSUE TITLE
Report incorrect types of return values and function arguments

### ISSUE THREAD

**Issue by hazzus** [VKCOM/noverify#516]
## Code Example

```php
function f() : int {
  return "hello";
}

function g(array $x) {}

g(1);
```

## Actual Behavior

No warnings

## Expected Behavior

Warning about `return "hello"`, where `"hello"` doesn't match `int` return type of `f`
Warning about `g(1)`, where `1` doesn't match `array` argument type of `g`

PHP7 actually fails stage of execution of such code with uncaught TypeError. But with some exceptions:
```php
function u(string $x) {}

u(1)
```
It's executable without errors, but semantically may be not right

**Comment by i582** [comment]
Will be tracked further in #1123.
