### ISSUE TITLE
Improve self type handling in traits

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#533]
## Code Example

```php
<?php

trait Singleton {
  /**
   * @var self
   */
  private static $instance = null;

  /**
   * @return self
   */
  public static function instance() {
    if (!self::$instance) {
      self::$instance = new self();
    }

    return self::$instance;
  }
}

class Foo {
  use Singleton;
  public function f() {}
}

Foo::instance()->f();
```

## Actual Behavior

Undefined method error. `Foo::instance()` result type is resolved into `\Singleton|null`.

## Expected Behavior

No undefined method error. `Foo::instance()` result type contains `\Foo`.

Note that if we change `self` to `static` in `Singleton` definition, linter will behave as expected. This issue is about `self` type annotation that should behave identically in this case (although some manual/docs reading is suggested).

**Comment by YuriyNasretdinov** [comment]
It will be the same as static in this case, but not in some others though. E.g. in a class Bar extends Foo the "self" still would be Foo, whereas "static" would be Bar. At least that's my understanding.

**Comment by quasilyte** [comment]
That's correct. But we still need to fix `self` handling as it refers to the current trait name instead of the class that "used" the trait.
