### ISSUE TITLE
arrayAccess false positive for ArrayAccess-typed param

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#556]
## Code Example

```php
<?php

/**
 * @param \ArrayAccess|array $v
 */
function f($v) {
  return $v[10];
}
```

## Actual Behavior

```
MAYBE   arrayAccess: Array access to non-array type \ArrayAccess|mixed[] at /home/isharipov/CODE/php/hello.php:7
  return $v[10];
         ^^
```

## Expected Behavior

No warnings.

Probably a regression of some kind?

**Comment by quasilyte** [comment]
The problem is that `Implements` doesn't handle interfaces.

Instead of checking that `T` implements ArrayAccess as a class, we probably want to check whether `T` defines methods we're looking for (so it can be ArrayAccess interface itself or any other interface that extends it).

**Comment by YuriyNasretdinov** [comment]
I don't think that's how PHP itself works. I am pretty sure that a variable will be treated as ArrayAccess'ible only when it implements \ArrayAccess and not just the required methods.

**Comment by quasilyte** [comment]
The main reasoning is that ArrayAccess type should be recognized as something that is compatible with ArrayAccess interface.

**Comment by YuriyNasretdinov** [comment]
Yes, I agree with that. I just wanted to warn against treating everything that implements methods of \ArrayAccess as something that in fact implements \ArrayAccess as that's not what PHP runtime is looking for.
