### ISSUE TITLE
Find mismatching @return annotations

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#561]
## Code Example

```php
    /**
     * Set the current local namespace.
     * @param array|null $namespace (default: null)
     * @return array|null
     */
    public function setNamespace(array $namespace = null)
    {
        $this->namespace = $namespace;
    }
```

## Actual Behavior

No warnings.

## Expected Behavior

Warning about not returning anything from a function that promised to return something (except null) in its phpdoc.

**Comment by i582** [comment]
Will be tracked further in #1123.
