### ISSUE TITLE
For non-void functions, forbid bare return

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#563]
## Code Example

```php
/**
 * @return string|null
 */
function f($x) {
  if (!$x) {
    return; // Better to write as "return null"
  }
  // ...
}
```

## Actual Behavior

No warnings.

## Expected Behavior

Suggest explicit `return null`. Functions with void results should be ignored.

**Comment by i582** [comment]
Will be tracked further in #1123.
