### ISSUE TITLE
Add support of disable/ignore comment to skip error at line

### ISSUE THREAD

**Issue by proggga** [VKCOM/noverify#58]
## Code Example
for example in pylint we have this comments
```python
import config.logging_settings # pylint: disable=W0611

import config.logging_settings # pylint: disable=unused-import
```
Sometimes you have strange cases, where linter is not good, but it works
for example old, legacy code 

I want some kind of this exclude line by special comment with disable name
```php
$this->gmail->sendEmail($email, $subject);

Here I got:
ERROR   Call to undefined method {}->sendEmail()
```
I want
```php
$this->gmail->sendEmail($email, subject);  // noverify: disable=call-undefined-method
```

**Comment by YuriyNasretdinov** [comment]
In these cases you need to just put PHPDoc and not write these kinds of comments as it allows to do refactorings more easily afterwards. So I am against it as there is already an option to disable linter for a specific commit once with a commit message that contains "@linter disable".

**Comment by quasilyte** [comment]
There is a little more customization now.

It's unlikely that there will be any line-level directives though.
