### ISSUE TITLE
Type inference for closures

### ISSUE THREAD

**Issue by i582** [VKCOM/noverify#609]
Currently, the type for the closure arguments is not inferred, but that would be helpful.

There are two main direction, I think:
1. handle only built-in functions like sorting.
2. try to handle even custom functions.

## Code Example

```php
$d = [10, 56, 32, 12];

usort($d, function($a, $b)
{
  exprtype($a, "int");
  exprtype($b, "int");

  if ($a == $b) {
    return 0;
  }
  return ($a < $b) ? -1 : 1;
});
```

## Actual Behavior
The types are wrong.

## Expected Behavior
The types are correct.

**Comment by quasilyte** [comment]
Custom functions behavior can't be tracked without good flow analysis which we currently don't have.

I would start from the builtin functions like `array_map`.

Param type hints help in some cases, but PHP doesn't have typed arrays support, so one can't express `[]Foo` type, for example. This is why we need this feature.

In normal functions, phpdoc can help, but it's less obvious how to associate free-floating comments with the lambda.
