### ISSUE TITLE
No way to filter out issues by severity

### ISSUE THREAD

**Issue by sergey-shambir** [VKCOM/noverify#66]
There are issues with low severity level (e.g. 'MAYBE').
Is there way to specify minimal severity level to filter issues with lower severity?

**Comment by quasilyte** [comment]
There is no such feature right now. The severity level is something subjective and it's not very reliable.

Does explicit `-allow-checks` list work for you?

**Comment by sergey-shambir** [comment]
Yes, `-allow-checks` works too.
Actually I'm working on patch which adds `-min-level` option support.
However, it's looks like current levels are not sequental. I'll look to my patch again tomorrow.
