### ISSUE TITLE
Add "-exclude" argument

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/noverify#7]
## Description

Each modern project contains a `vendor` directory. If include the `src` directory, then the linter produces a lot of false positive errors associated with external dependencies. If add the whole project, the linter will start to produce errors in the dependencies (from the vendor directory).

## Suggest

Add "-exclude=./vendor -exclude=./tests -exclude=./resources" (etc)  arguments for exclude directories from the report.

**Comment by YuriyNasretdinov** [comment]
There are already exists exclude argument :). You need to pass regular expression there, as it is only a single parameter. E.g. -exclude='vendor|tests'

**Comment by SerafimArts** [comment]
Oh, yep, this is lost in the depths of the documentation: https://github.com/VKCOM/noverify#disable-some-reports =\

My bad
