### ISSUE TITLE
Add new type of alerts: useless if or same variable set

### ISSUE THREAD

**Issue by proggga** [VKCOM/noverify#70]
## Code Example

```php
<?php
define('SOME_CONSTANT', 100500);
$param = $argv[1];
$value = mcGet('some_key');
if (!$data) {
  if ($param) {
    $data = SOME_CONSTANT;
  } else {
    $data = SOME_CONSTANT;
  }
}
echo $data . PHP_EOL;
function mcGet($key) {
  return null;
}
```

In this case $data has same value in all if cases
I want add check to add alert for unnecessary if or same set variable in all if branches

**Comment by quasilyte** [comment]
Detecting duplicated conditional statement branches seems doable, with some heuristics it shouldn't give false positives. At least this particular case seems simple to detect.

**Comment by i582** [comment]
We currently have a dupBranchBody check that can cover this case.
