### ISSUE TITLE
Make stubs loading faster

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#702]
Golden tests are slow due to this. If we make stubs loading faster, we'll get a noticeable boost.

Ideas:
* (Maybe hard to implement) Don't parse embedded stubs, generate maps right away during the `go:generate`.
* Don't use cache-related code during stubs loading (it apparently only slows down the stubs loading, but profiling is suggested).

**Comment by i582** [comment]
I looked at this package. It seems to me that we already have a fairly simple solution, 
I see no reason to add another library and rewrite part of the code.

**Comment by i582** [comment]
Now we have no problems with the speed of tests, so I consider this issue to be outdated.
