### ISSUE TITLE
Erroneous type inference when using operators like +=

### ISSUE THREAD

**Issue by i582** [VKCOM/noverify#720]
## Code Example

```php
function foo() {
    $a = 0;
    $a += 12.56;
}
```

## Actual Behavior
`$a` is `int`

## Expected Behavior
`$a` is `float`

Most likely the matter is that we do not handle assignment operators like `+=`.

**Comment by i582** [comment]
@YuriyNasretdinov What do you think about handling such assignments?

**Comment by YuriyNasretdinov** [comment]
@i582 they need to be handled :). Probably the same way that ExprType() currently handles +, *, etc
