### ISSUE TITLE
Add support for @mixin annotation

### ISSUE THREAD

**Issue by vbifial** [VKCOM/noverify#782]
## Code Example

```php
<?php

class Foo {
    public function method() {}
}

/**
 * Class Bar
 * @mixin Foo
 */
class Bar {
    public function run()
    {
        $this->method();
    }
}
```

## Actual Behavior

```
<critical> ERROR   undefined: Call to undefined method {\Bar}->method() at Sample.php:14
        $this->method();
               ^^^^^^
```

## Expected Behavior

No errors found

**Comment by YuriyNasretdinov** [comment]
Couldn't you just write "use Foo;" and define Foo as a trait instead?

**Comment by vbifial** [comment]
Ofcource I could, but there is a lot of legacy code with this type of syntax.
Moreover, there is "behaviors" mechanism like one in Yii2. Behavior classes doesn't connect to owner via "use" clause.
