### ISSUE TITLE
Make NoVerify more CI-friendly

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#83]
Several users reported that NoVerify is too noisy by default and has some false positives that are hard to fix inside linter without introducing false negatives.

The proposal is to add CI-friendly mode that sacrifices some reports for the less false negative rate. More strict (currently the only one) mode can be enabled later when the majority of the project complies to a linter.

Right now I don't know the best way to do it and adding another configuration flag may be sub-optimal. Maybe we need to change default behavior accordingly and only after that consider whether we need very strict mode (needs more feedback and investigation). Discussions are welcome.

Below are some specific complaints, grouped by the check name.

## undefined check

* Don't warn on undefined method/property if the type is unknown. In other words, don't say something like `property {}->foo does not exist`. For the most strict mode (current) it could be nice to warn that type might not always be what the user expects and that it can't be inferred from the source code, but for CI it's more trouble than it worth.

* Don't warn on special global variables like `$argv` in global scope. 90% of their usages are inside scripts that are not included from other scripts, so `global` statement can be considered too pedantic there. For strict mode it's OK though.

**Comment by quasilyte** [comment]
Probably should also address issues that #68 tried to solve.
(Ability to configure what issues to print.)

**Comment by i582** [comment]
I believe that by now we have improved the CI-friendly well.

The strict mode was added and the checks that are enabled by default were revised.
Also, in view of the fact that some checks were divided into several, this allows you to more finely configure NoVerify.
