### ISSUE TITLE
Remove Lmicroseconds from the logger flags

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#847]
```
2020/12/10 13:38:00.552688 Started
=>
2020/12/10 13:38:00 Started
```
This would need a [log.SetFlags](https://golang.org/pkg/log/#SetFlags) call.

**Comment by YuriyNasretdinov** [comment]
Why do you want to remove the microseconds? It is much easier to tell how much time each step consumes. Without microseconds you will only be able to see these timings with a microsecond precision which is definitely not enough on any fast enough machine.

**Comment by quasilyte** [comment]
Why every user that runs the linter needs to care about microseconds?
You don't get microseconds logs when you run a compiler or most other tools.

It can be enabled in debug/verbose mode, but by default, it looks redundant.

**Comment by YuriyNasretdinov** [comment]
Sure, but then you need to have an option to do that in my opinion, not just remove the option alltogether :)
