### ISSUE TITLE
Support `static` and `$this` types

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#89]
## Code Example

```php
class Foo
{
    /** @return $this */
    public function bar()
    {
        return $this;
    }

    /** @return static */
    public function baz()
    {
        return new static();
    }
}
```

## Actual Behavior

For `static`, NoVerify behaves like it's `self`, which is not correct (since we need late static binding in those cases instead of an early one).

For `$this` it infers the "identity" type of `$this`, which is not useful. Whether it should map it into `self` or `static` is an open question though. I would stick to `static` in this case, but it could be more conservative to use `self` there, at least for now.

## Expected Behavior

`static` resolved into derived type on the use spots.
`$this` is either ignored since NoVerify can infer actual return types for `return $this` or mapped into some other type. It's also possible to handle `$this` in a special way, but it doesn't seem to yield any benefits over other forms (static/self).

See also https://github.com/yiisoft/yii2/issues/7045.

**Comment by YuriyNasretdinov** [comment]
Yes, this is a very good feature to have. It is already supported by PHPStorm as well. I am not really sure how one is going to implement it though but it will definitely require some kind of late static binding in noverify itself :)

**Comment by YuriyNasretdinov** [comment]
$this must be the same type as static because of how instances work
