### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by Anandh21** [VKCOM/noverify#927]
## Code Example

```php
➜   ZSH.    bin ls
noverify
```

## Actual Behavior

I want to run noverify for my project but the command is not found 

noverify check -cache-dir=$HOME/tmp/cache/noverify /path/to/your/project/root
zsh: command not found: noverify

## Expected Behavior

// Description of what you expected

**Comment by YuriyNasretdinov** [comment]
You need to add the binary location (e.g. $HOME/go/bin) to your $PATH, in your case presumably it would be in .zshrc
